"""Finite lifecycle events; this is intentionally not an event bus."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


PLAN_READY = "PLAN_READY"
PLAN_BLOCKED_BY_USER_INTENT = "PLAN_BLOCKED_BY_USER_INTENT"
TOOL_FAILED = "TOOL_FAILED"
EDIT_APPLIED = "EDIT_APPLIED"
EDIT_FAILED = "EDIT_FAILED"
FINISH_REQUESTED = "FINISH_REQUESTED"
VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
INCREMENTAL_VERIFIED = "INCREMENTAL_VERIFIED"
INCREMENTAL_PARTIAL = "INCREMENTAL_PARTIAL"
FINAL_VERIFIED = "FINAL_VERIFIED"
FINAL_PARTIAL = "FINAL_PARTIAL"
VERIFICATION_REGRESSED = "VERIFICATION_REGRESSED"
TARGET_FAILED = "TARGET_FAILED"
VERIFICATION_UNVERIFIED = "VERIFICATION_UNVERIFIED"
REPLAN_REQUIRED = "REPLAN_REQUIRED"
CONTINUE_EXECUTION = "CONTINUE_EXECUTION"
USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"
USER_CONFIRMED = "USER_CONFIRMED"
MAX_STEPS_REACHED = "MAX_STEPS_REACHED"
UNRECOVERABLE_FAILURE = "UNRECOVERABLE_FAILURE"


@dataclass(frozen=True)
class AgentEvent:
    type: str
    reason: str = ""
    payload: dict[str, Any] = field(default_factory=dict)
